image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build MiroslavGPT.AWS --configuration Release --no-restore --runtime linux-x64
    - dotnet publish MiroslavGPT.AWS --configuration Release --no-build --output ./publish --runtime linux-x64
  artifacts:
    paths:
      - ./publish

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - cd publish
    - zip -r lambda.zip .
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://lambda.zip
    - aws lambda update-function-configuration --function-name $FUNCTION_NAME --environment "Variables={TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN,OPENAI_API_KEY=$OPENAI_API_KEY,SECRET_KEY=$SECRET_KEY,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME,BOT_NAME=$BOT_NAME,MAX_TOKENS=$MAX_TOKENS}"
  only:
    - master
  environment:
    name: production
