image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - deploy-azure

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build MiroslavGPT.Azure --configuration Release --no-restore
    - dotnet publish MiroslavGPT.Azure --configuration Release --no-build --output ./publish/azure
  artifacts:
    paths:
      - ./publish

deploy_azure:
  stage: deploy-azure
  image: mcr.microsoft.com/dotnet/sdk:latest
  before_script:
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - apt-get install curl && curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install nodejs
    - npm install -g azure-functions-core-tools@4 --unsafe-perm true
  script:
    - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - cd publish/azure
    - func azure functionapp publish $AZURE_FUNCTION_APP_NAME --dotnet-version 6.0 --no-build --csharp
    - CONNECTION_STRING="AccountEndpoint=$COSMOSDB_ENDPOINT_URL;AccountKey=$COSMOSDB_PRIMARY_KEY;ApiKind=Gremlin"
    - az functionapp config appsettings set --name $AZURE_FUNCTION_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --settings "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" "OPENAI_API_KEY=$OPENAI_API_KEY" "SECRET_KEY=$SECRET_KEY" "COSMOSDB_CONNECTION_STRING=$CONNECTION_STRING" "COSMOSDB_DATABASE_NAME=$COSMOSDB_DATABASE_NAME" "COSMOSDB_CONTAINER_NAME=$COSMOSDB_CONTAINER_NAME" "TELEGRAM_BOT_USERNAME=$TELEGRAM_BOT_USERNAME" "MAX_TOKENS=$MAX_TOKENS" > /dev/null
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://<your-azure-function-url>.azurewebsites.net
