image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - deploy-aws
  - deploy-azure

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build MiroslavGPT.AWS --configuration Release --no-restore --runtime linux-x64
    - dotnet build MiroslavGPT.Azure --configuration Release --no-restore
    - dotnet publish MiroslavGPT.AWS --configuration Release --no-build --output ./publish/aws --runtime linux-x64
    - dotnet publish MiroslavGPT.Azure --configuration Release --no-build --output ./publish/azure
  artifacts:
    paths:
      - ./publish

deploy_aws:
  stage: deploy-aws
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - cd publish/aws
    - zip -r lambda.zip .
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://lambda.zip
    - aws lambda update-function-configuration --function-name $FUNCTION_NAME --environment "Variables={TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN,OPENAI_API_KEY=$OPENAI_API_KEY,SECRET_KEY=$SECRET_KEY,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME,TELEGRAM_BOT_USERNAME=$TELEGRAM_BOT_USERNAME,MAX_TOKENS=$MAX_TOKENS}"
  only:
    - master
  when: manual
  environment:
    name: production

deploy_azure:
  stage: deploy-azure
  image: mcr.microsoft.com/azure-cli:latest
  before_script:
    - npm install --global azure-functions-core-tools@core
  script:
    - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - cd publish/azure
    - func init --worker-runtime dotnet --no-git
    - func azure functionapp publish $AZURE_FUNCTION_APP_NAME --dotnet-version 6.0 --no-build
    - CONNECTION_STRING="AccountEndpoint=$COSMOSDB_ENDPOINT_URL;AccountKey=$COSMOSDB_PRIMARY_KEY;ApiKind=Gremlin"
    - az functionapp config appsettings set --name $AZURE_FUNCTION_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --settings "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN OPENAI_API_KEY=$OPENAI_API_KEY SECRET_KEY=$SECRET_KEY COSMOSDB_CONNECTION_STRING=$CONNECTION_STRING COSMOSDB_DATABASE_NAME=$COSMOSDB_DATABASE_NAME COSMOSDB_CONTAINER_NAME=$COSMOSDB_CONTAINER_NAME TELEGRAM_BOT_USERNAME=$BOT_NAME MAX_TOKENS=$MAX_TOKENS"
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://<your-azure-function-url>.azurewebsites.net
